<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<META HTTP-EQUIV='pragma' CONTENT='no-cache'> 
<META HTTP-EQUIV='Cache-Control' CONTENT='no-cache, must-revalidate'>
<META HTTP-EQUIV='expires' CONTENT='0'>
<script type="text/javascript">
	var projectName = '<%=request.getContextPath()%>';
</script>


<script type="text/javascript" src="<%=request.getContextPath()%>/webbuilder/controls/ext/ext-all.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/webbuilder/controls/ext/locale/ext-lang-zh_CN.js"></script>
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/webbuilder/controls/ext/resources/css/ext-all.css" />


<script type="text/javascript" src="<%=request.getContextPath()%>/pub/uip/common/scripts/md5.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/common/js/base64.js"></script>


<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/common/css/font.css" />
<link rel="stylesheet" type="text/css" media="all" href="<%=request.getContextPath()%>/common/css/default.css" />
